/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  addFolder: IDL.Func(
    [IDL.Text, IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null })],
    [IDL.Record({ id: IDL.Nat, name: IDL.Text, category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }), createdAt: IDL.Int })],
    []
  ),
  updateFolder: IDL.Func(
    [IDL.Nat, IDL.Text],
    [IDL.Opt(IDL.Record({ id: IDL.Nat, name: IDL.Text, category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }), createdAt: IDL.Int }))],
    []
  ),
  deleteFolder: IDL.Func([IDL.Nat], [IDL.Bool], []),
  getFolder: IDL.Func(
    [IDL.Nat],
    [IDL.Opt(IDL.Record({ id: IDL.Nat, name: IDL.Text, category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }), createdAt: IDL.Int }))],
    ['query']
  ),
  getAllFolders: IDL.Func(
    [],
    [IDL.Vec(IDL.Record({ id: IDL.Nat, name: IDL.Text, category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }), createdAt: IDL.Int }))],
    ['query']
  ),
  getFoldersByCategory: IDL.Func(
    [IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null })],
    [IDL.Vec(IDL.Record({ id: IDL.Nat, name: IDL.Text, category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }), createdAt: IDL.Int }))],
    ['query']
  ),
  addMovie: IDL.Func(
    [
      IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat,
      IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }),
      IDL.Opt(IDL.Nat)
    ],
    [IDL.Record({
      id: IDL.Nat, title: IDL.Text, description: IDL.Text, posterUrl: IDL.Text,
      videoLink: IDL.Text, genre: IDL.Text, year: IDL.Nat,
      category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }),
      folderId: IDL.Opt(IDL.Nat), createdAt: IDL.Int
    })],
    []
  ),
  updateMovie: IDL.Func(
    [
      IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat,
      IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }),
      IDL.Opt(IDL.Nat)
    ],
    [IDL.Opt(IDL.Record({
      id: IDL.Nat, title: IDL.Text, description: IDL.Text, posterUrl: IDL.Text,
      videoLink: IDL.Text, genre: IDL.Text, year: IDL.Nat,
      category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }),
      folderId: IDL.Opt(IDL.Nat), createdAt: IDL.Int
    }))],
    []
  ),
  deleteMovie: IDL.Func([IDL.Nat], [IDL.Bool], []),
  getMovie: IDL.Func(
    [IDL.Nat],
    [IDL.Opt(IDL.Record({
      id: IDL.Nat, title: IDL.Text, description: IDL.Text, posterUrl: IDL.Text,
      videoLink: IDL.Text, genre: IDL.Text, year: IDL.Nat,
      category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }),
      folderId: IDL.Opt(IDL.Nat), createdAt: IDL.Int
    }))],
    ['query']
  ),
  getAllMovies: IDL.Func(
    [],
    [IDL.Vec(IDL.Record({
      id: IDL.Nat, title: IDL.Text, description: IDL.Text, posterUrl: IDL.Text,
      videoLink: IDL.Text, genre: IDL.Text, year: IDL.Nat,
      category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }),
      folderId: IDL.Opt(IDL.Nat), createdAt: IDL.Int
    }))],
    ['query']
  ),
  getMoviesByCategory: IDL.Func(
    [IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null })],
    [IDL.Vec(IDL.Record({
      id: IDL.Nat, title: IDL.Text, description: IDL.Text, posterUrl: IDL.Text,
      videoLink: IDL.Text, genre: IDL.Text, year: IDL.Nat,
      category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }),
      folderId: IDL.Opt(IDL.Nat), createdAt: IDL.Int
    }))],
    ['query']
  ),
  getMoviesByFolder: IDL.Func(
    [IDL.Nat],
    [IDL.Vec(IDL.Record({
      id: IDL.Nat, title: IDL.Text, description: IDL.Text, posterUrl: IDL.Text,
      videoLink: IDL.Text, genre: IDL.Text, year: IDL.Nat,
      category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }),
      folderId: IDL.Opt(IDL.Nat), createdAt: IDL.Int
    }))],
    ['query']
  ),
  searchMovies: IDL.Func(
    [IDL.Text],
    [IDL.Vec(IDL.Record({
      id: IDL.Nat, title: IDL.Text, description: IDL.Text, posterUrl: IDL.Text,
      videoLink: IDL.Text, genre: IDL.Text, year: IDL.Nat,
      category: IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null }),
      folderId: IDL.Opt(IDL.Nat), createdAt: IDL.Int
    }))],
    ['query']
  ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({ Bollywood: IDL.Null, Hollywood: IDL.Null, Gujarati: IDL.Null, Tollywood: IDL.Null });
  const Folder = IDL.Record({ id: IDL.Nat, name: IDL.Text, category: Category, createdAt: IDL.Int });
  const Movie = IDL.Record({
    id: IDL.Nat, title: IDL.Text, description: IDL.Text, posterUrl: IDL.Text,
    videoLink: IDL.Text, genre: IDL.Text, year: IDL.Nat, category: Category,
    folderId: IDL.Opt(IDL.Nat), createdAt: IDL.Int
  });
  return IDL.Service({
    addFolder: IDL.Func([IDL.Text, Category], [Folder], []),
    updateFolder: IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(Folder)], []),
    deleteFolder: IDL.Func([IDL.Nat], [IDL.Bool], []),
    getFolder: IDL.Func([IDL.Nat], [IDL.Opt(Folder)], ['query']),
    getAllFolders: IDL.Func([], [IDL.Vec(Folder)], ['query']),
    getFoldersByCategory: IDL.Func([Category], [IDL.Vec(Folder)], ['query']),
    addMovie: IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, Category, IDL.Opt(IDL.Nat)], [Movie], []),
    updateMovie: IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, Category, IDL.Opt(IDL.Nat)], [IDL.Opt(Movie)], []),
    deleteMovie: IDL.Func([IDL.Nat], [IDL.Bool], []),
    getMovie: IDL.Func([IDL.Nat], [IDL.Opt(Movie)], ['query']),
    getAllMovies: IDL.Func([], [IDL.Vec(Movie)], ['query']),
    getMoviesByCategory: IDL.Func([Category], [IDL.Vec(Movie)], ['query']),
    getMoviesByFolder: IDL.Func([IDL.Nat], [IDL.Vec(Movie)], ['query']),
    searchMovies: IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
