// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
import type { IDL } from '@icp-sdk/core/candid';
export const idlService: IDL.ServiceClass;
export const idlInitArgs: IDL.Type[];
export const idlFactory: ({ IDL }: { IDL: any }) => IDL.ServiceClass;
export const init: ({ IDL }: { IDL: any }) => IDL.Type[];

export type Category = { Bollywood: null } | { Hollywood: null } | { Gujarati: null } | { Tollywood: null };
export interface Folder { id: bigint; name: string; category: Category; createdAt: bigint; }
export interface Movie { id: bigint; title: string; description: string; posterUrl: string; videoLink: string; genre: string; year: bigint; category: Category; folderId: [] | [bigint]; createdAt: bigint; }
export interface _SERVICE {
  addFolder(name: string, category: Category): Promise<Folder>;
  updateFolder(id: bigint, name: string): Promise<[] | [Folder]>;
  deleteFolder(id: bigint): Promise<boolean>;
  getFolder(id: bigint): Promise<[] | [Folder]>;
  getAllFolders(): Promise<Folder[]>;
  getFoldersByCategory(category: Category): Promise<Folder[]>;
  addMovie(title: string, description: string, posterUrl: string, videoLink: string, genre: string, year: bigint, category: Category, folderId: [] | [bigint]): Promise<Movie>;
  updateMovie(id: bigint, title: string, description: string, posterUrl: string, videoLink: string, genre: string, year: bigint, category: Category, folderId: [] | [bigint]): Promise<[] | [Movie]>;
  deleteMovie(id: bigint): Promise<boolean>;
  getMovie(id: bigint): Promise<[] | [Movie]>;
  getAllMovies(): Promise<Movie[]>;
  getMoviesByCategory(category: Category): Promise<Movie[]>;
  getMoviesByFolder(folderId: bigint): Promise<Movie[]>;
  searchMovies(q: string): Promise<Movie[]>;
}
