/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface backendInterface {
    addFolder(name: string, category: any): Promise<any>;
    updateFolder(id: bigint, name: string): Promise<any>;
    deleteFolder(id: bigint): Promise<boolean>;
    getFolder(id: bigint): Promise<any>;
    getAllFolders(): Promise<any[]>;
    getFoldersByCategory(category: any): Promise<any[]>;
    addMovie(title: string, description: string, posterUrl: string, videoLink: string, genre: string, year: bigint, category: any, folderId: any): Promise<any>;
    updateMovie(id: bigint, title: string, description: string, posterUrl: string, videoLink: string, genre: string, year: bigint, category: any, folderId: any): Promise<any>;
    deleteMovie(id: bigint): Promise<boolean>;
    getMovie(id: bigint): Promise<any>;
    getAllMovies(): Promise<any[]>;
    getMoviesByCategory(category: any): Promise<any[]>;
    getMoviesByFolder(folderId: bigint): Promise<any[]>;
    searchMovies(q: string): Promise<any[]>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}

    async addFolder(name: string, category: any): Promise<any> {
        try { return await this.actor.addFolder(name, category); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async updateFolder(id: bigint, name: string): Promise<any> {
        try { return await this.actor.updateFolder(id, name); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async deleteFolder(id: bigint): Promise<boolean> {
        try { return await this.actor.deleteFolder(id); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getFolder(id: bigint): Promise<any> {
        try { return await this.actor.getFolder(id); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getAllFolders(): Promise<any[]> {
        try { return await this.actor.getAllFolders(); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getFoldersByCategory(category: any): Promise<any[]> {
        try { return await this.actor.getFoldersByCategory(category); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async addMovie(title: string, description: string, posterUrl: string, videoLink: string, genre: string, year: bigint, category: any, folderId: any): Promise<any> {
        try { return await this.actor.addMovie(title, description, posterUrl, videoLink, genre, year, category, folderId); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async updateMovie(id: bigint, title: string, description: string, posterUrl: string, videoLink: string, genre: string, year: bigint, category: any, folderId: any): Promise<any> {
        try { return await this.actor.updateMovie(id, title, description, posterUrl, videoLink, genre, year, category, folderId); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async deleteMovie(id: bigint): Promise<boolean> {
        try { return await this.actor.deleteMovie(id); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getMovie(id: bigint): Promise<any> {
        try { return await this.actor.getMovie(id); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getAllMovies(): Promise<any[]> {
        try { return await this.actor.getAllMovies(); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getMoviesByCategory(category: any): Promise<any[]> {
        try { return await this.actor.getMoviesByCategory(category); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async getMoviesByFolder(folderId: bigint): Promise<any[]> {
        try { return await this.actor.getMoviesByFolder(folderId); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
    async searchMovies(q: string): Promise<any[]> {
        try { return await this.actor.searchMovies(q); }
        catch(e) { if (this.processError) this.processError(e); throw e; }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
